resource_types:
  - name: slack_notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/smichard/personal_website.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
  check_every: 60s

- name: image_source
  type: docker-image
  source:
    repository: nginx
    tag: latest
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/personal_website.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.5.0

- name: docker_hub
  type: docker-image
  source:
    email: {{docker_hub_email}}
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: smichard/personal_website

- name: aws_target
  type: s3
  source:
    endpoint: {{aws_endpoint}}
    bucket: code-sym-releases
    regexp: production/personal_website-(.*)-(.*).tar.gz
    access_key_id: {{aws_key}}
    secret_access_key: {{aws_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

jobs:
  - name: build-container
    public: true
    serial: true
    plan:
    - get: app_sources
      trigger: true
    - get: image_source
      trigger: true
    - put: docker_hub
      params:
        build: app_sources/
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Prod: New personal_website container pushed to docker hub The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
            https://deploy.michard.de/teams/main/pipelines/personal_website
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Prod: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            https://deploy.michard.de/builds/$BUILD_ID

  - name: aws-backup
    public: true
    serial: true
    plan:
    - get: version
    - get: app_sources
      passed: [ build-container ]
      trigger: true
    - task: create-artifact
      file: app_sources/ci/tasks/create_artifact.yml
    - put: aws_target
      params:
        acl: public-read
        file: ./artifact/personal_website-*-*.tar.gz

  - name: bump-version-minor
    public: true
    plan:
    - aggregate:
      - get: app_sources
        passed: [ aws-backup ]
        trigger: true
      - get: version
      - put: version
        params:
          bump: minor

  - name: minor
    public: true
    plan:
    - aggregate:
      - get: version
      - put: version
        params:
          bump: minor

  - name: major
    public: true
    plan:
    - aggregate:
      - get: version
      - put: version
        params:
          bump: major
