resource_types:
  - name: slack_notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
- name: website_sources_dev
  type: git
  source:
    uri: https://github.com/smichard/personal_website.git
    branch: dev
    username: {{github_username}}
    password: {{github_password}}
  check_every: 60s

- name: website_sources
  type: git
  source:
    uri: https://github.com/smichard/personal_website.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
  check_every: 60s

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/personal_website.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.5.0

- name: docker_hub_dev
  type: docker-image
  source:
    email: {{docker_hub_email}}
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: {{docker_hub_dev_repository}}

- name: docker_hub
  type: docker-image
  source:
    email: {{docker_hub_email}}
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: {{docker_hub_repository}}

- name: S3_target
  type: s3
  source:
    endpoint: {{s3_endpoint}}
    bucket: releases
    regexp: release_history/personal_website-(.*)-(.*).tar.gz
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

jobs:
  - name: build-website-dev
    public: true
    serial: true
    plan:
    - get: website_sources_dev
      trigger: true
    - put: docker_hub_dev
      params:
        path: website_sources_dev/
      on_failure:
        do:
        - task: hue_red
          file: website_sources/ci/tasks/hue_red.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Personal website: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        do:
        - task: hue_green
          file: website_sources/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Personal website: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.

  - name: merge-dev-to-master
    public: true
    plan:
    - get: website_sources_dev
      passed:
      - build-website-dev
    - put: website_sources
      params:
        merge: true
        repository: website_sources_dev
        tag: version/version
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Personal website: Dev branch failed to merge with master branch. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Personal website: Dev branch succesfully merged to master branch. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.

  - name: build-website
    public: true
    serial: true
    plan:
    - get: website_sources
      passed:
      - merge-dev-to-master
      trigger: true
    - put: docker_hub
      params:
        path: website_sources/
      on_failure:
        do:
        - task: hue_red
          file: website_sources/ci/tasks/hue_red.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Personal website: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        do:
        - task: hue_green
          file: website_sources/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              Personal website: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. New docker container available on docker hub:
              https://hub.docker.com/u/smichard/

  - name: ecs-backup
    public: true
    serial: true
    plan:
    - get: version
    - get: website_sources
      passed:
      - build-website
      trigger: true
    - task: create-artifact
      file: website_sources/ci/tasks/create_artifact.yml
    - put: S3_target
      params:
        acl: public-read
        file: ./artifact/personal_website-*-*.tar.gz
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Personal website: Artifact could not be uploaded to S3 target. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Personal website: Artifact succesfully uploaded to S3 target.
  - name: bump-version-minor
    public: true
    plan:
    - aggregate:
      - get: website_sources
        passed:
        - ecs-backup
        trigger: true
      - get: version
      - put: version
        params:
          bump: minor

  - name: minor
    public: true
    plan:
    - aggregate:
      - get: version
      - put: version
        params:
          bump: minor

  - name: major
    public: true
    plan:
    - aggregate:
      - get: version
      - put: version
        params:
          bump: major
